name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Backend
      run: |
        docker build -t tew56789/todo-backend ./backend
        docker push tew56789/todo-backend

    - name: Build & Push Frontend
      run: |
        docker build -t tew56789/todo-frontend ./frontend
        docker push tew56789/todo-frontend
